/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.caribbeanmarinabeachclub.controlbrazaletescaribbean.view;

import com.caribbeanmarinabeachclub.controlbrazaletescaribbean.controller.Build_Brazaletes;
import com.caribbeanmarinabeachclub.controlbrazaletescaribbean.models.brazaletes.Brazalete_Invitado;
import com.caribbeanmarinabeachclub.controlbrazaletescaribbean.models.brazaletes.Brazalete_Propietario;
import com.caribbeanmarinabeachclub.controlbrazaletescaribbean.models.brazaletes.Brazalete_alquilado;
import com.caribbeanmarinabeachclub.controlbrazaletescaribbean.models.brazaletes.Condicion;
import com.caribbeanmarinabeachclub.controlbrazaletescaribbean.models.brazaletes.FormaPago;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import com.caribbeanmarinabeachclub.controlbrazaletescaribbean.models.brazaletes.Turno;
import com.caribbeanmarinabeachclub.controlbrazaletescaribbean.models.dbcon.DataBase_manager;
import java.awt.Color;
import java.util.Arrays;
import javax.swing.ButtonGroup;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author diego
 */
public class RegistrarBrazalete extends javax.swing.JPanel implements ChangeListener{

    public JPanel getMainPane() {
        return mainPane;
    }

    /**
     * Creates new form RegistrarBrazaletePane
     */
    public RegistrarBrazalete() {
        initComponents();
        dataBase_manager = new DataBase_manager();
        build_Brazaletes = new Build_Brazaletes();
        bs_usd_bcv = build_Brazaletes.getPrice_ves_usd();
        bcvLabel.setText("Tasa BCV: " + bs_usd_bcv);

        // COMBOBOX MODEL CREATION
        ComboBoxModel turnoComboBoxModel = new DefaultComboBoxModel(new Object[]{Turno.TURNO_DIURNO, Turno.TURNO_NOCTURNO});
        turnoComboBox.setModel(turnoComboBoxModel);
        ComboBoxModel formaPagoComboBoxModel = new DefaultComboBoxModel(new Object[]{FormaPago.PAGO_BS, FormaPago.PAGO_USD});
        formaPagoComboBox.setModel(formaPagoComboBoxModel);

        //BUTTON GROUP DESIGNATION
        representaIngresoTglBtn.setBackground(new Color(153, 255, 153));
        representaIngresoTglBtn.setForeground(new Color(0, 0, 51));

        //RADION BTN GROUP
        ButtonGroup btng = new ButtonGroup();
        btng.add(propietarioRdoBtn);
        btng.add(alquiladoRdiobtn);
        btng.add(invitadoRdoBtn);

        //SPINNER MODEL
        SpinnerNumberModel spinnerModel = new SpinnerNumberModel(1, 1, 120, 1);
        cantidadSpinner.setModel(spinnerModel);

        //cantidadSpinner.addChangeListener(stateChanged(cantidadSpinner.)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(300, 0), new java.awt.Dimension(300, 0), new java.awt.Dimension(300, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 32767));
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        responsableTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        turnoComboBox = new javax.swing.JComboBox<>();
        alquiladoRdiobtn = new javax.swing.JRadioButton();
        propietarioRdoBtn = new javax.swing.JRadioButton();
        invitadoRdoBtn = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        serialBrazaleteTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inmuebleTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        representaIngresoTglBtn = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        serialAutorizacionTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        formaPagoComboBox = new javax.swing.JComboBox<>();
        montoPagadoLabel = new javax.swing.JLabel();
        montoPagadoTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        observacionTextArea = new javax.swing.JTextPane();
        jLabel12 = new javax.swing.JLabel();
        entregarBtn = new javax.swing.JButton();
        refPagoTextField = new javax.swing.JTextField();
        bcvLabel = new javax.swing.JLabel();
        refPagoLabel = new javax.swing.JLabel();
        cantidadSpinner = new javax.swing.JSpinner();
        refPagoLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        seriales_brazalete_textArea = new javax.swing.JTextPane();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        mainPane.setBackground(new java.awt.Color(0, 0, 51));
        mainPane.setMinimumSize(new java.awt.Dimension(800, 600));
        mainPane.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo caribbean.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CBT CARIBBEAN BRAZALET TRACKER V1.1.0");

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setOpaque(true);

        jLabel5.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Seleccione condicion");

        jLabel3.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Responsable");

        jLabel4.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Turno");

        turnoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        alquiladoRdiobtn.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        alquiladoRdiobtn.setForeground(new java.awt.Color(255, 255, 255));
        alquiladoRdiobtn.setText("ALQUILADO");
        alquiladoRdiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alquiladoRdiobtnActionPerformed(evt);
            }
        });

        propietarioRdoBtn.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        propietarioRdoBtn.setForeground(new java.awt.Color(255, 255, 255));
        propietarioRdoBtn.setText("PROPIETARIO");
        propietarioRdoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propietarioRdoBtnActionPerformed(evt);
            }
        });

        invitadoRdoBtn.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        invitadoRdoBtn.setForeground(new java.awt.Color(255, 255, 255));
        invitadoRdoBtn.setText("INVITADO");
        invitadoRdoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invitadoRdoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(propietarioRdoBtn)
                    .addComponent(invitadoRdoBtn)
                    .addComponent(alquiladoRdiobtn))
                .addGap(93, 93, 93)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(turnoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(responsableTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 29, Short.MAX_VALUE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(propietarioRdoBtn)
                        .addGap(44, 44, 44)
                        .addComponent(invitadoRdoBtn)
                        .addGap(44, 44, 44)
                        .addComponent(alquiladoRdiobtn)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(194, 194, 194)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(responsableTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(turnoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(39, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setLayout(null);
        jPanel2.add(serialBrazaleteTextField);
        serialBrazaleteTextField.setBounds(190, 10, 165, 34);

        jLabel6.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Serial brazalete");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(6, 0, 131, 56);

        jLabel7.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Inmueble");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(6, 62, 96, 56);
        jPanel2.add(inmuebleTextField);
        inmuebleTextField.setBounds(187, 74, 171, 34);

        jLabel13.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Representa ingreso");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(410, 80, 166, 34);

        representaIngresoTglBtn.setFont(new java.awt.Font("Roboto Condensed", 1, 12)); // NOI18N
        representaIngresoTglBtn.setText("SI");
        representaIngresoTglBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                representaIngresoTglBtnActionPerformed(evt);
            }
        });
        jPanel2.add(representaIngresoTglBtn);
        representaIngresoTglBtn.setBounds(580, 80, 83, 24);

        jLabel9.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Serial autorizacion");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(6, 118, 149, 56);
        jPanel2.add(serialAutorizacionTextField);
        serialAutorizacionTextField.setBounds(190, 140, 171, 34);

        jLabel11.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Forma de pago");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(6, 188, 140, 56);

        formaPagoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        formaPagoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formaPagoComboBoxActionPerformed(evt);
            }
        });
        jPanel2.add(formaPagoComboBox);
        formaPagoComboBox.setBounds(190, 200, 171, 36);

        montoPagadoLabel.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        montoPagadoLabel.setForeground(new java.awt.Color(255, 255, 255));
        montoPagadoLabel.setText("Monto pagado");
        jPanel2.add(montoPagadoLabel);
        montoPagadoLabel.setBounds(0, 260, 123, 56);
        jPanel2.add(montoPagadoTextField);
        montoPagadoTextField.setBounds(220, 270, 140, 34);

        jScrollPane1.setViewportView(observacionTextArea);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(410, 160, 270, 90);

        jLabel12.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Observacion");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(410, 110, 123, 56);

        entregarBtn.setBackground(new java.awt.Color(153, 255, 153));
        entregarBtn.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        entregarBtn.setForeground(new java.awt.Color(0, 0, 51));
        entregarBtn.setText("ENTREGAR");
        entregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entregarBtnActionPerformed(evt);
            }
        });
        jPanel2.add(entregarBtn);
        entregarBtn.setBounds(470, 420, 120, 56);
        jPanel2.add(refPagoTextField);
        refPagoTextField.setBounds(150, 340, 210, 34);

        bcvLabel.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        bcvLabel.setForeground(new java.awt.Color(255, 255, 255));
        bcvLabel.setText("Tasa BCV: 36,19");
        jPanel2.add(bcvLabel);
        bcvLabel.setBounds(470, 10, 147, 44);

        refPagoLabel.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        refPagoLabel.setForeground(new java.awt.Color(255, 255, 255));
        refPagoLabel.setText("Cantidad");
        jPanel2.add(refPagoLabel);
        refPagoLabel.setBounds(0, 400, 130, 30);
        jPanel2.add(cantidadSpinner);
        cantidadSpinner.setBounds(150, 400, 64, 30);

        refPagoLabel1.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        refPagoLabel1.setForeground(new java.awt.Color(255, 255, 255));
        refPagoLabel1.setText("Ref. pago");
        jPanel2.add(refPagoLabel1);
        refPagoLabel1.setBounds(0, 340, 130, 30);

        jScrollPane2.setViewportView(seriales_brazalete_textArea);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(380, 280, 320, 130);

        javax.swing.GroupLayout mainPaneLayout = new javax.swing.GroupLayout(mainPane);
        mainPane.setLayout(mainPaneLayout);
        mainPaneLayout.setHorizontalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPaneLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(97, 97, 97)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filler2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(mainPaneLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        mainPaneLayout.setVerticalGroup(
            mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPaneLayout.createSequentialGroup()
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPaneLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(mainPaneLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPaneLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, 972, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

   

    private void representaIngresoTglBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_representaIngresoTglBtnActionPerformed
        JComponent container[] = {formaPagoComboBox, montoPagadoTextField, refPagoTextField};
        Arrays.asList(container).forEach(a -> {
            a.setEnabled(representaIngresoFlag);
        });

        if (representaIngresoTglBtn.getText().equalsIgnoreCase("SI")) {
            representaIngresoTglBtn.setText("NO");
            representaIngresoTglBtn.setBackground(new Color(204, 0, 0));
            representaIngresoTglBtn.setForeground(new Color(255, 255, 255));
            representaIngresoFlag = true;

        } else {
            representaIngresoTglBtn.setText("SI");
            representaIngresoTglBtn.setBackground(new Color(153, 255, 153));
            representaIngresoTglBtn.setForeground(new Color(0, 0, 51));
            representaIngresoFlag = false;
        }

    }//GEN-LAST:event_representaIngresoTglBtnActionPerformed

    public void enableDisableElements(boolean use) {
        JComponent container[] = {formaPagoComboBox, montoPagadoTextField, refPagoTextField, representaIngresoTglBtn, serialAutorizacionTextField};
        Arrays.asList(container).forEach(a -> {
            a.setEnabled(use);
        });

    }

    private void entregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entregarBtnActionPerformed
        validarCampos();

        build_Brazaletes.build_define_instances(condicion);
        String refPagoFlag = (refPagoLabel.getText().equalsIgnoreCase("Ref. pago") ? refPagoTextField.getText() : "");
        String billeteSerial = (refPagoLabel.getText().equalsIgnoreCase("Serial Billete") ? refPagoTextField.getText() : "");
        double montoPago = (!montoPagadoTextField.getText().isEmpty() ? Double.parseDouble(montoPagadoTextField.getText()) : 0.0);

        build_Brazaletes.build_brazalete(inmuebleTextField.getText(), (Turno) turnoComboBox.getSelectedItem(),
                Integer.parseInt(serialBrazaleteTextField.getText()), observacionTextArea.getText(),
                responsableTextField.getText().toUpperCase(), serialAutorizacionTextField.getText(),
                (FormaPago) formaPagoComboBox.getSelectedItem(), montoPago,
                refPagoFlag, (representaIngresoTglBtn.getText().equalsIgnoreCase("SI")), billeteSerial);

//        System.out.println(refPagoTextField.getText());
//////        Brazalete_Invitado brazalete_Invitado = (Brazalete_Invitado) build_Brazaletes.getBrazalete_invitado();
//        //dataBase_manager.saveBrazalete(brazalete_Invitado);
//        Brazalete_alquilado brazalete_Invitado = (Brazalete_alquilado) build_Brazaletes.getBrazalete_alquilado();
//        System.out.println(brazalete_Invitado.toString());
//        Brazalete_Propietario brazalete_Invitado = (Brazalete_Propietario) build_Brazaletes.getBrazalete_propietario();
        switch (condicion) {
            case PROPIETARIO ->
                dataBase_manager.saveBrazalete((Brazalete_Propietario) build_Brazaletes.getBrazalete_propietario());
            case ALQUILADO ->
                dataBase_manager.saveBrazalete((Brazalete_alquilado) build_Brazaletes.getBrazalete_alquilado());
            default ->
                dataBase_manager.saveBrazalete((Brazalete_Invitado) build_Brazaletes.getBrazalete_invitado());
        }

        build_Brazaletes.clearAll();
        JTextField containerTextField[] = {responsableTextField, serialBrazaleteTextField, inmuebleTextField,
            serialAutorizacionTextField, montoPagadoTextField, refPagoTextField};

        Arrays.asList(containerTextField).forEach(a -> {
            a.setText("");
        });
        JOptionPane.showMessageDialog(null, "GUARDADO!", "EXITO", JOptionPane.OK_OPTION);

    }//GEN-LAST:event_entregarBtnActionPerformed

    public void validarCampos() {
        JTextField containerTextField[] = {responsableTextField, serialBrazaleteTextField, inmuebleTextField,
            serialAutorizacionTextField, montoPagadoTextField, refPagoTextField};

        JTextField containetTextFieldPropietario[] = {responsableTextField, serialBrazaleteTextField, inmuebleTextField};

        JRadioButton container[] = {propietarioRdoBtn, invitadoRdoBtn, alquiladoRdiobtn};

        Arrays.asList(container).forEach(c -> {
            if (!propietarioRdoBtn.isSelected() && !invitadoRdoBtn.isSelected() && !alquiladoRdiobtn.isSelected()) {
                JOptionPane.showMessageDialog(null, "DEBES SELECCIONAR UNA CONDICION", "ERROR", JOptionPane.ERROR_MESSAGE);
                throw new NullPointerException();
            }

        });

        if (condicion == Condicion.PROPIETARIO || (condicion == Condicion.INVITADO && representaIngresoTglBtn.getText().equals("NO"))) {
            Arrays.asList(containetTextFieldPropietario).forEach(c -> {
                if (c.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "DEBES LLENAR TODOS LOS CAMPOS", "ERROR", JOptionPane.ERROR_MESSAGE);
                    throw new NullPointerException();
                }
            });
        } else {

            Arrays.asList(containerTextField).forEach(c -> {
                if (c.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "DEBES LLENAR TODOS LOS CAMPOS", "ERROR", JOptionPane.ERROR_MESSAGE);
                    throw new NullPointerException();
                }
            });
        }

    }
    private int k = 1;
    private void formaPagoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formaPagoComboBoxActionPerformed
        if ((FormaPago) formaPagoComboBox.getSelectedItem() == FormaPago.PAGO_BS) {
            refPagoLabel.setText("Ref. pago");
        } else {
            refPagoLabel.setText("Serial Billete");
        }
    }//GEN-LAST:event_formaPagoComboBoxActionPerformed

    private void propietarioRdoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propietarioRdoBtnActionPerformed
        enableDisableElements(false);
        evaluarCondicionSeleccionada(Condicion.PROPIETARIO);
    }//GEN-LAST:event_propietarioRdoBtnActionPerformed

    private void alquiladoRdiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alquiladoRdiobtnActionPerformed
        enableDisableElements(true);
        evaluarCondicionSeleccionada(Condicion.ALQUILADO);
    }//GEN-LAST:event_alquiladoRdiobtnActionPerformed

    private void invitadoRdoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invitadoRdoBtnActionPerformed
        enableDisableElements(true);
        evaluarCondicionSeleccionada(Condicion.INVITADO);
    }//GEN-LAST:event_invitadoRdoBtnActionPerformed

    public void evaluarCondicionSeleccionada(Condicion condicion) {
        switch (condicion) {
            case PROPIETARIO -> {
                condicionSelected = true;
                representaIngresoTglBtn.setText("NO");
                representaIngresoTglBtn.setEnabled(false);
                this.condicion = Condicion.PROPIETARIO;
            }

            case ALQUILADO -> {
                condicionSelected = true;
                representaIngresoTglBtn.setText("SI");
                representaIngresoTglBtn.setEnabled(false);
                representaIngresoTglBtn.setBackground(new Color(153, 255, 153));
                representaIngresoTglBtn.setForeground(new Color(0, 0, 51));
                this.condicion = Condicion.ALQUILADO;
            }
            default -> {
                condicionSelected = true;
                representaIngresoTglBtn.setText("SI");
                representaIngresoTglBtn.setEnabled(true);

                this.condicion = Condicion.INVITADO;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton alquiladoRdiobtn;
    private javax.swing.JLabel bcvLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JSpinner cantidadSpinner;
    private javax.swing.JButton entregarBtn;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JComboBox<String> formaPagoComboBox;
    private javax.swing.JTextField inmuebleTextField;
    private javax.swing.JRadioButton invitadoRdoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel mainPane;
    private javax.swing.JLabel montoPagadoLabel;
    private javax.swing.JTextField montoPagadoTextField;
    private javax.swing.JTextPane observacionTextArea;
    private javax.swing.JRadioButton propietarioRdoBtn;
    private javax.swing.JLabel refPagoLabel;
    private javax.swing.JLabel refPagoLabel1;
    private javax.swing.JTextField refPagoTextField;
    private javax.swing.JToggleButton representaIngresoTglBtn;
    private javax.swing.JTextField responsableTextField;
    private javax.swing.JTextField serialAutorizacionTextField;
    private javax.swing.JTextField serialBrazaleteTextField;
    private javax.swing.JTextPane seriales_brazalete_textArea;
    private javax.swing.JComboBox<String> turnoComboBox;
    // End of variables declaration//GEN-END:variables

    //FLAG VARIABLES
    private boolean representaIngresoFlag;
    private boolean condicionSelected = false;

    //CAMPOS PARA CONSTRUIR BRAZALETE
    private Build_Brazaletes build_Brazaletes;
    private double bs_usd_bcv;
    private Condicion condicion;
    private Turno turno;
    private FormaPago formaPago;
    private int i=0;

    //BASE DE DATOS
    private DataBase_manager dataBase_manager;

    @Override
    public void stateChanged(ChangeEvent e) {
        if(i<(int)cantidadSpinner.getValue()){
            System.out.println("Incrementando");
        }else{
            System.out.println("Decrementando");
        }
        i = (int) cantidadSpinner.getValue();
    }
}
